on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish project to Demo env of Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 59bdb4e22f71d50cd67b45aa7bd53dff
          projectName: vim-canvas-demo-app-demo
          directory: dist
          workingDirectory: vim-canvas-demo-app-react